pipeline {
    triggers {
        pollSCM('H 15 * * *')
    }

    options {
        buildDiscarder(logRotator(numToKeepStr: '5', artifactNumToKeepStr: '5'))
    }

   stage('Checkout from SCM GIT') {
    checkout([$class: 'GitSCM', branches: [[name: '*/master']], 
              doGenerateSubmoduleConfigurations: false, extensions: [], 
              submoduleCfg: [], 
              userRemoteConfigs: [[url: 'https://github.com/dhoolmahe/IIHTFinalCaseStudy.git']]])
     echo 'Git checkout succeeded'
   }
   
   stage('Build Docker Image') {
      // Build image from Docker File path
      sh 'docker build -f "./project-mgr-ui/Dockerfile" -t dhoolmahi/project-mgr-ui:"$BUILD_NUMBER" ./project-mgr-ui/'
   }
   
   stage('Pushing Image into Docker Hub') {
	   	withCredentials([string(credentialsId: 'docker-pwd', variable: 'DockerPwd')]) {
	    	sh "docker login -u sankarthik30 -p ${DockerPwd}"
		}
		
   		sh 'docker push sankarthik30/project-mgr-ui:"$BUILD_NUMBER" '
   }
   
   stage('Run Docker container') {
   	
   	  //Remove existing containers
      sh 'docker ps --format "{{.ID}}" --filter name=project-mgr-ui | sort -u | xargs docker rm -f'
      
      sh 'docker run --rm -d -p 8085:80/tcp --name project-mgr-ui project-mgr-ui:"$BUILD_NUMBER" '
   }
}